name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu:20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --platform linux/amd64 -t call_chets:$(date +%s)
