# This is a basic workflow that is manually triggered

name: commit id

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'build commit ID'
        default: 'test'
        required: false
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: get commit id
      run: git rev-parse HEAD > latest.txt
